### ISSUE TITLE
 udisks-glue: segfault

### ISSUE THREAD

**Issue by ghost** [fernandotcl/udisks-glue#5] opened 2012-02-21 19:35 UTC
Hello,

From time to time my external USB HD just disappear for no apparent reason. And I have to start udisks-glue again.

In dmesg, I see this:

> [27047.535014] usb 3-1.3.4: reset high-speed USB device number 7 using ehci_hcd
> [27047.627715] usb 3-1.3.4: device firmware changed
> [27047.628665] sd 8:0:0:0: Device offlined - not ready after error recovery
> [27047.629401] usb 3-1.3.4: USB disconnect, device number 7
> [27047.982712] usb 3-1.3.4: new high-speed USB device number 8 using ehci_hcd
> [27048.076653] usb 3-1.3.4: New USB device found, idVendor=059b, idProduct=0470
> [27048.076663] usb 3-1.3.4: New USB device strings: Mfr=1, Product=11, SerialNumber=5
> [27048.076690] usb 3-1.3.4: Product: Storage
> [27048.076695] usb 3-1.3.4: Manufacturer: JMicron
> [27048.076699] usb 3-1.3.4: SerialNumber: 801130168383
> [27048.079938] scsi9 : usb-storage 3-1.3.4:1.0
> [27050.446683] scsi 9:0:0:0: Direct-Access     ST932032 5AS                   PQ: 0 ANSI: 2 CCS
> [27068.942897] not responding...
> [27077.187535] sd 9:0:0:0: [sdd] READ CAPACITY failed
> [27077.187566] sd 9:0:0:0: [sdd]  Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
> [27077.187574] sd 9:0:0:0: [sdd]  Sense Key : Unit Attention [current] 
> [27077.187604] sd 9:0:0:0: [sdd]  Add. Sense: Not ready to ready change, medium may have changed
> [27079.938147] sd 9:0:0:0: [sdd] Test WP failed, assume Write Enabled
> [27082.688057] sd 9:0:0:0: [sdd] Asking for cache data failed
> [27082.688070] sd 9:0:0:0: [sdd] Assuming drive cache: write through
> [27113.938565] not responding...
> [27120.910175] CPU2: Package power limit normal
> [27120.910184] CPU3: Package power limit normal
> [27120.910217] CPU1: Package power limit normal
> [27120.910226] CPU0: Package power limit normal
> [27126.631758] sd 9:0:0:0: [sdd] 625142448 512-byte logical blocks: (320 GB/298 GiB)
> [27126.636152] sd 9:0:0:0: [sdd] Attached SCSI disk
> [27157.471612] usb 3-1.3.4: reset high-speed USB device number 8 using ehci_hcd
> [27157.564323] usb 3-1.3.4: device firmware changed
> [27157.564966] sd 9:0:0:0: Device offlined - not ready after error recovery
> [27157.565007] sd 9:0:0:0: [sdd] Unhandled error code
> [27157.565012] sd 9:0:0:0: [sdd]  Result: hostbyte=DID_ABORT driverbyte=DRIVER_OK
> [27157.565020] sd 9:0:0:0: [sdd] CDB: Read(10): 28 00 25 42 ea 00 00 00 08 00
> [27157.565061] end_request: I/O error, dev sdd, sector 625142272
> [27157.565092] Buffer I/O error on device sdd, logical block 78142784
> [27157.565170] sd 9:0:0:0: rejecting I/O to offline device
> [27157.565176] sd 9:0:0:0: killing request
> [27157.565732] usb 3-1.3.4: USB disconnect, device number 8
> [27157.643407] usb 3-1.3.4: new high-speed USB device number 9 using ehci_hcd
> [27157.736788] usb 3-1.3.4: New USB device found, idVendor=059b, idProduct=0470
> [27157.736820] usb 3-1.3.4: New USB device strings: Mfr=1, Product=11, SerialNumber=5
> [27157.736826] usb 3-1.3.4: Product: Storage
> [27157.736830] usb 3-1.3.4: Manufacturer: JMicron
> [27157.736834] usb 3-1.3.4: SerialNumber: 5E17FFFFFFFF
> [27157.738715] scsi10 : usb-storage 3-1.3.4:1.0
> [27157.789744] udisks-glue[2379]: segfault at 10 ip 0000000000405174 sp 00007fff38a446d8 error 4 in udisks-glue[400000+8000]
> [27158.782675] scsi 10:0:0:0: Direct-Access     ST932032 5AS                   PQ: 0 ANSI: 2 CCS
> [27158.871551] sd 10:0:0:0: [sdd] 625142448 512-byte logical blocks: (320 GB/298 GiB)

It looks like my HD is failing somehow, but udisks-glue should not:)

Don't know what information you need, here is my config:

> cat ~/.config/udisks-glue/config 
> 
> filter disks {
>     optical = false
>     usage = filesystem
> }
> 
> match disks {
>     automount = true
>     automount_options = { flush, noatime, "fmask=033", "dmask=022" }
> }

**Comment by fernandotcl** [comment] 2012-02-21 20:42
Hi,

This is certainly a bug, as we shouldn't crash even though your disk may be failing or bad. I'm not able to reproduce it. If you are, please try the following:
- Make sure you have debugging symbols in the binary. You can compile it yourself to make sure those symbols aren't stripped.
- Enable core dumping before launching udisks-glue. In bash, that can be done with "ulimit -c unlimited", then launch udisks-glue from that shell (preferably with -f -v and logging the output, e.g., udisks-glue -f -v 2>&1 | tee udisks-glue.log).
- Make udisks-glue crash. This should probably result in a file named "core" in your home directory.
- Run "gdb -c /path/to/core /path/to/udisks-glue". In gdb, run "bt full". Then please make that output available.
- If you logged udisks-glue's stdout/err output, please make that available somewhere too.

With that information we may be able to tell whether this is a bug in udisks-glue itself or somewhere else, and if it's a bug in udisks-glue, we can have a clue of where the problem may be.

Thanks,

**Comment by ghost** [comment] 2012-02-23 08:13
I will do that, and actually I'm already trying since the other day, but
looks like, reporting the bug fixed it for me ;)

I'll report back as soon as I have something.

**Comment by ghost** [comment] 2012-02-26 12:49
Eventually, I got the segfault!

You'll find attach the archive containing the files you asked:

| tar tvf udisks-glue-segfault-debug.tar.lzma --lzma
| drwxr-x--- sam/sam           0 2012-02-26 13:38 udisks-glue-segfault-debug/
| -rw------- sam/sam      761856 2012-02-26 13:30 udisks-glue-segfault-debug/core
| -rw-r----- sam/sam         961 2012-02-26 13:35 udisks-glue-segfault-debug/udisks-glue.log
| -rw-r----- sam/sam        3076 2012-02-26 13:38 udisks-glue-segfault-debug/gdb-bt-full-output
| -rw-r----- sam/sam        4602 2012-02-26 13:32 udisks-glue-segfault-debug/dmesg

Thanks

**Comment by fernandotcl** [comment] 2012-02-26 16:23
Hi, thanks! Unfortunately, though, GitHub seems to filter e-mail attachments. Could you please paste the text files on something like nopaste or pastebin?

**Comment by ghost** [comment] 2012-02-26 16:50
gdb-bt-full-output -> http://paste.debian.net/157664/

part of dmesg -> http://paste.debian.net/157665/

udisks-glue.log -> http://paste.debian.net/157666/

**Comment by fernandotcl** [comment] 2012-02-26 18:01
Thanks! It should be fixed in 00476123.

**Closed as completed by fernandotcl** 2012-02-26 18:01 UTC
